### PR TITLE
Update support to K8s V1.11 and CSI v0.3.0

### PR DESCRIPTION
**Pull request by jtt17**
**What this PR does / why we need it**:

Add support to K8s V1.11 and CSI v0.3.0

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

fixes : fixed the bug when creating volume, the 'CapacityBytes' of return type volumeinfo is wrong,,K8s v1.11 may check this value, that lead to create volume failed ,  'CapacityBytes' should multiply 1024^3

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by jtt17** [comment]
file 'csi-configmap-opensdsplugin.yaml' is a vendor file?    it will be ok if  i delete the change of it ?  @xing-yang

**Comment by jtt17** [comment]
I update vendor file by Go dep tools .
Env: Windows Server 2016 Standard 
After run cmd 'dep ensure -v' in Git Bash , it's weird that lots of vendor files changed or delete .  I only commit the change of file 'csi.pb.go' and 'Gopkg.lock',  Is this work?

**Comment by jtt17** [comment]
Do I need to remove the change of 'Gopkg.lock' except the content about CSI manually ?  because 'Gopkg.lock' changed a lot , corresponding, the change of vendor file did  not commit

**Comment by xing-yang** [comment]
I'd suggest using Ubuntu v16.04 or higher as that is what we've suggested in our docs.  Git Bash on Windows may produce different results.  You can take a look of this: https://github.com/opensds/nbp/pull/118.  Gopkg.lock should be submitted.  You also need to change k8s version.  Right now it is 1.8.2, not 1.11.

**Comment by jtt17** [comment]
i do dep in ubuntu and change All of K8s.io/**** to version 1.11.0 , i dont konw whether these files change is right . Is there a flag to judge whether it is done?

**Pull request closed without merging**
