### PR TITLE
[Vmware/NGC] Fix for List Snapshot issue #345

### LINKED ISSUE #345: [Vmware/NGC] Not listing all snapshots for a volume
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When there are multiple snapshots for a volume NGC backup window list shows only one snap when we select that volume.
**What you expected to happen**:
All snapshots of the volume should be selected.
**How to reproduce it (as minimally and precisely as possible)**:
ngc_snaphotlist
ngc_snaphotlist1

**Anything else we need to know?**:
NA
**Environment**:
- NBP version:v0.10.0
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by NajmudheenCT**
**What this PR does / why we need it**:
NGC plugin do not list snapshots in vmware client. RCA is when there is snapshot creation results in error , adding this snapshot in to list is result in java exception as some of the fields are not present.
Fix is to check if the status of snapshot is error then do not add that in the snapshot list.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #345 

**testing Notes** : 
Tested with multiple snapshots and when snapshots having error status.
log snippet below

Feb 03, 2020 3:37:24 PM org.opensds.vmware.ngc.adapters.opensds.OpenSDS listSnapshot
INFO: OpenSDS Snapshot List: [SnapshotMO [name=test200130152031662, id=5f6f3427-480e-4a25-bdb3-118f8367c449, healthStatus=available, capacity=1073741824, parentID=49c7ea7d-533b-43ae-b917-ab9297453165, timeStamp=2020-01-30T15:20:34]  [name=test200130151854618, id=3abb0385-4b03-4af9-a6d2-298263d9f203, healthStatus=error,  timeStamp=2 020-01-30T15:20:34]]

### CODE REVIEW

**Comment by sushanthakumar** [comment]
One doubt, only successfully created snapshots should be shown or all snapshots should be shown
Hope we do similar way as we do for volume listing

**Comment by NajmudheenCT** [comment]
> One doubt, only successfully created snapshots should be shown or all snapshots should be shown
> Hope we do similar way as we do for volume listing

Only successfully created snapshots, basically the available snaphots which can be used for recovery.

**Comment by sushanthakumar** [comment]
LGTM

**Comment by NajmudheenCT** [comment]
> @NajmudheenCT how the user will come to know, there is an error in the snapshot? should we not show the status in the front end?
> Pls check!

Thanks for noticing the status field. As of now we have issue to show the status in UI. I will create an issue for this. This fix is required as of now bcause without fix if there is any snapshot with error , no snapshots is howed in UII .

**Comment by skdwriting** [comment]
@NajmudheenCT please add the issue # here

**Comment by NajmudheenCT** [comment]
> @NajmudheenCT please add the issue # here

https://github.com/opensds/nbp/issues/354

**Pull request merged**
